
AWS_UPLOAD_BUCKET = "quixdoc"

AWS_UPLOAD_USERNAME = "CFE_user_nick"

AWS_UPLOAD_GROUP = "CFE_AwesomeGroup"

AWS_UPLOAD_REGION = 'us-east-1'

AWS_UPLOAD_ACCESS_KEY_ID = "AKIAJ5KSMV4WK7GHANTQ"

AWS_UPLOAD_SECRET_KEY = "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"
